dataset:
  name: BGS
  prune: True  # If true, prunes edges that are further than two steps from the target labels

training:
  epochs: 50
  optimiser:
    algorithm: adam
    weight_decay: 0.005
    learn_rate: 0.01
  use_cuda: True  # If true, model is trained on GPU

rgcn:
  model: e-rgcn
  num_layers: 2  # Number of graph convolution layers
  node_embeddings: 32  # Size of node embeddings

evaluation:
  final_run: True  # If true, evaluates model on test set. Otherwise, validation set is used.
